### ISSUE TITLE
SendMessage Error

### ISSUE THREAD

**Issue by rayenking** [MinhHuyDev/fbchat-v2#20]
- - - - -
<!DOCTYPE html><html lang="en" id="facebook"><head><title>Error</title><meta charset="utf-8" /><meta http-equiv="Cache-Control" content="no-cache" /><meta name="robots" content="noindex,nofollow" /><style nonce="wfWasHre">html, body { color: #333; font-family: 'Lucida Grande', 'Tahoma', 'Verdana', 'Arial', sans-serif; margin: 0; padding: 0; text-align: center;}
#header { height: 30px; padding-bottom: 10px; padding-top: 10px; text-align: center;}
#icon { width: 30px;}
.core { margin: auto; padding: 1em 0; text-align: left; width: 904px;}
h1 { font-size: 18px;}
p { font-size: 13px;}
.footer { border-top: 1px solid #ddd; color: #777; float: left; font-size: 11px; padding: 5px 8px 6px 0; width: 904px;}</style></head><body><div id="header"><a href="//www.facebook.com/"><img id="icon" src="//static.facebook.com/images/logos/facebook_2x.png" /></a></div><div class="core"><h1>Sorry, something went wrong.</h1><p>We&#039;re working on getting this fixed as soon as we can.</p><p><a id="back" href="//www.facebook.com/">Go back</a></p><div class="footer"> Meta &#169; 2024 &#183; <a href="//www.facebook.com/help/?ref=href052">Help</a></div></div><script nonce="wfWasHre">
              document.getElementById("back").onclick = function() {
                if (history.length > 1) {
                  history.back();
                  return false;
                }
              };
            </script></body></html>
Exception in thread Thread-5 (send):
Traceback (most recent call last):
  File "C:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\ryana\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ryana\OneDrive\Desktop\Works\fbchat-v2\src\__sendMessage.py", line 33, in send
    self.sendMessage()
  File "C:\Users\ryana\OneDrive\Desktop\Works\fbchat-v2\src\__sendMessage.py", line 113, in sendMessage
    self.sendRequests()
  File "C:\Users\ryana\OneDrive\Desktop\Works\fbchat-v2\src\__sendMessage.py", line 121, in sendRequests
    sendRequests = json.loads(sendRequests.split("for (;;);")[1])
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by MinhHuyDev** [comment]
Thanks for issue. I will fix it soon.

**Comment by MinhHuyDev** [comment]
Thanks for issue. I will fix it soon.
